#!/bin/sh
#
# 2015 ungleich GmbH (cdist at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# get os infos
os=$(cat "$__global/explorer/os")

if grep -q "^__file/etc/postfix/" "$__messages_in"; then
    case "${os}" in
        debian)
            echo /etc/init.d/postgrey restart
            echo /etc/init.d/postfix reload
        ;;
        archlinux)
            echo "/usr/bin/systemctl restart postgrey"
            echo "/usr/bin/systemctl reload postfix"
        ;;
    esac
fi
