#!/bin/sh
#
# 2015 ungleich GmbH (cdist at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat $__global/explorer/os)
osversion=$(cat "$__global/explorer/os_version")

# make sure postgrey and postfix is installed
__package postfix
require="__package/postfix" __package postgrey

# There is a bug that prevents restarting postgrey correctly and,
# unfortunately, its patch is not present on outdated versions of
# Postgrey (like the available on Debian Wheezy).

case "$os" in
    debian)
        case $osversion in
            7*)
				require="__package/postgrey" __file "/etc/init.d/postgrey" \
				        --source "$__type/files/init.d_file" --mode 0755
            ;;
        esac
esac

# place custom whitelist for Microsoft Exchange Online Protection (EOP)
require="__package/postgrey" __file "/etc/postgrey/whitelist_clients.local" \
        --source "$__type/files/custom_whitelist" --mode 0644

# make sure postgrey is enabled on startup
require="__package/postgrey" __start_on_boot postgrey --state present


# enable postgrey in postfix configuration
require="__package/postgrey" __postfix_postconf smtpd_recipient_restrictions --value "permit_mynetworks permit_sasl_authenticated reject_non_fqdn_recipient reject_unauth_destination check_policy_service inet:127.0.0.1:10023"
